--- UPDATED ON 11-4-2021 | NEEDED TO FOREFULLY CHANGE THE CHECKSUM!

NDefines.NGame.LAG_DAYS_FOR_LOWER_SPEED = 100
NDefines.NGame.LAG_DAYS_FOR_PAUSE = 60

--- DETROPAT ADDITIONS
NDefines_Graphics.NGraphics.CAPITAL_ICON_CUTOFF = 800						-- 1100 
NDefines_Graphics.NGraphics.DRAW_MAP_OBJECTS_CUTOFF = 250 					-- 550 
NDefines_Graphics.NGraphics.MAP_BUILDINGS_SHRINK_DISTANCE = 100				-- 180

NDefines.NGame.COMBAT_LOG_MAX_MONTHS = 6 --12
